# Generated by Django 3.1.4 on 2020-12-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('thumb', models.ImageField(default='default.png', upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
