# Generated by Django 3.2.4 on 2021-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
