# Generated by Django 3.2.4 on 2021-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
