# Generated by Django 3.2.4 on 2021-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
